# Generated by Django 4.1 on 2022-11-30 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='Date Joined')),
                ('last_login', models.DateField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superuser?')),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=60, verbose_name='Last Name')),
                ('bio', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Bio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
            ],
            options={
                'verbose_name_plural': 'Homie Chat Users',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=44, unique=True)),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='room_videos')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
